name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - master  # or main, based on your default

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3

        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
